### PR TITLE
docs(validator): added equalTo rule

### PR DESCRIPTION
**Pull request by popovicieduard**

### CODE REVIEW

**Comment by popovicieduard** [comment]
Docs for https://github.com/adonisjs/validator/pull/98

**Comment by RomainLanz** [comment]
Oops! 😓 

Could you please rebase your PR? 😄

**Comment by popovicieduard** [comment]
@RomainLanz Done. sorry for taking this long.

**Comment by RomainLanz** [comment]
Thanks! 💜

**Pull request merged**
