### PR TITLE
feat: add deployment article

### PR DESCRIPTION
**Pull request by LeCoupa**
Here is the documentation file to set up Adonis 5 on production. Hope it helps!

* Initial Server Setup
* Clone Your Adonis Repository
* Set up Mysql
* Build for Production
* Set up Nginx with SSL.
* Set up Your Continuous Deployment Process with Github Actions

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @LeCoupa! 👋 

Thanks for your contribution.

The article you have written is a great fit as an independent blog post on your own blog or a platform like [dev.to](https://dev.to/).

The AdonisJS documentation has to be more in-depth explain the fundamentals around deployment that can be applied with any hosting and CI/CD setup.

I will give this PR a pass for now.

**Comment by LeCoupa** [comment]
@RomainLanz do you plan on having a section about deployment? Many people are asking about this on Discord. I thought a guide would help a lot.

**Comment by thetutlage** [comment]
Yes, we will write some guides around the same shortly

**Comment by LeCoupa** [comment]
I could work on the guide for deployment if you want to. Just tell me. In this case, I would try to fix the following issues:

- Explain the fundamentals of deployment more in depth.
- Make it work any hosting and CI/CD setup.

**Pull request closed without merging**
