### PR TITLE
Updated web guard documentation

### PR DESCRIPTION
**Pull request by ConsoleTVs**
Small fixes to the documentation of the web guards. There could still be improvements to be made, but it's 3:30 AM and I want to sleep. Let me know if I should add anything else. I am quite interested in the project.

### CODE REVIEW

**Review by RomainLanz — APPROVED** [review]

**Comment by RomainLanz** [comment]
Thanks! 💜

**Comment by ConsoleTVs** [comment]
Hey @RomainLanz , thanks for the merge! Would it be too much to ask for a `hacktoberfest-accepted` label on this PR? There's no need to set the project topic to hacktoberfest, using this label is enough to help me towards this year's edition!

Nevertheless; I am gaining more interest on this project. I only briefly used the last version of adonis to make a websocket package for flutter that implemented adonis' protocol but I feel this new version is quite a good one. I would like to help the project in any way. Is there any area I could help with? I don't mind if it's code or docs. I'm proficient enough in typescript if code was needed.

**Comment by thetutlage** [comment]
@ConsoleTVs Done 😄

**Comment by ConsoleTVs** [comment]
Such a commitment guys, thanks a lot!

I'll keep an eye at what to improve in this project. Feel free to make any suggestions on the core or any official package you feel there's the need for most help. Thanks a gain to you both for the amazing work!

**Pull request merged**
