### PR TITLE
docs(hash): adds hash documentation to digging deeper

### PR DESCRIPTION
**Pull request by Craytor**
Have added docs for the hashing functionality and have added it under digging deeper.

### CODE REVIEW

**Comment by thetutlage** [comment]
We have to create another category called `Security` and move it their. The security will cover more topics like

- `Encryption`
- `Hashing`
- `Signed URLs`
- and parts of shield.

**Comment by Craytor** [comment]
@thetutlage sounds good, do you want me to move this there and start working on the missing items?

**Comment by thetutlage** [comment]
Yup! It be will nice to have a new category **Security** and move it there. Also, to ensure that the docs are consistent with the rest of the website, we may have to do a bit of back and forth

**Comment by Craytor** [comment]
No problem. I will get started and advise upon updates so I can use feedback to improve.

**Comment by thetutlage** [comment]
Hey @Craytor. Are you still up on this? If not, then I can plan to begin working on it

**Comment by Craytor** [comment]
> Hey @Craytor. Are you still up on this? If not, then I can plan to begin working on it

My apologies, I've been a bit busy IRL. Feel free to tackle this if you haven't already. I do plan to jump on board and contribute docs in the future as time permits.

**Pull request closed without merging**
